### ISSUE TITLE
fails compiling bootstrap 2.3

### ISSUE THREAD

**Issue by ptcc** [BramvdKroef/clessc#15]
When compiling twitter bootstrap 2.3, fails with the following error:
Line 2, Column 8 Parse Error: Found "#font > #family > .serif" when expecting a mixin, nested ruleset, or property

thats on the mixins.less file

**Comment by artnikpro** [comment]
It fails with latest bootstrap 3.3.5.

    lessc resources/assets/css/less/bootstrap/bootstrap.less -o test.css 
    Segmentation fault: 11

**Comment by BramvdKroef** [comment]
Try it again with the latest changes. I was able to compile bootstrap 3.3.5. I also added an update so it doesn't fail on a double semicolon. 

I thought I had sourcemaps working in Firefox. I'll see if I can get it working in Chrome.

**Comment by artnikpro** [comment]
Great! Now it's compiling bootstrap.

As for sourcemaps, I've stumbled that the compiler lacks one little feature for complete happiness =). In my project I need to compile less like this

    clessc resources/app/assets/css/less/bootstrap/bootstrap.less -fo public/app/assets/css/bootstrap.css --source-map=public/app/assets/css/bootstrap.css.map

This gives me `/*# sourceMappingURL=public/app/assets/css/bootstrap.css.map */` in the end of bootstrap.css. But I need the URL to be like this `/app/assets/css/bootstrap.css.map` 

To workaround this I have to append an extra command in order to add one more url to the end of file

    && echo '/*# sourceMappingURL=/app/assets/css/bootstrap.css.map */' >> public/app/assets/css/bootstrap.css

so it would be great if there was an option like `--source-map-url` which Node's compiler has.

Thanks

**Comment by TristanBrotherton** [comment]
Sourcemap URL was added in recent commits.
